#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/vscode/.dotfiles/ammonite/predef.sc" "/home/vscode/.ammonite/predef.sc"
handle_file_ln "/home/vscode/.dotfiles/bash_profile" "/home/vscode/.bash_profile"
handle_file_ln "/home/vscode/.dotfiles/bashrc" "/home/vscode/.bashrc"
handle_file_ln "/home/vscode/.dotfiles/bundle/config" "/home/vscode/.bundle/config"
handle_file_ln "/home/vscode/.dotfiles/cabal/config" "/home/vscode/.cabal/config"
handle_file_ln "/home/vscode/.dotfiles/cargo/config" "/home/vscode/.cargo/config"
handle_file_ln "/home/vscode/.dotfiles/config/alacritty/alacritty.yml" "/home/vscode/.config/alacritty/alacritty.yml"
handle_file_ln "/home/vscode/.dotfiles/config/aria2/aria2.conf" "/home/vscode/.config/aria2/aria2.conf"
handle_file_ln "/home/vscode/.dotfiles/config/fish" "/home/vscode/.config/fish"
handle_file_ln "/home/vscode/.dotfiles/config/kglobalshortcutsrc" "/home/vscode/.config/kglobalshortcutsrc"
handle_file_ln "/home/vscode/.dotfiles/config/khotkeysrc" "/home/vscode/.config/khotkeysrc"
handle_file_ln "/home/vscode/.dotfiles/config/kitty" "/home/vscode/.config/kitty"
handle_file_ln "/home/vscode/.dotfiles/config/krunnerrc" "/home/vscode/.config/krunnerrc"
handle_file_ln "/home/vscode/.dotfiles/config/kwinrc" "/home/vscode/.config/kwinrc"
handle_file_ln "/home/vscode/.dotfiles/config/neofetch/config.conf" "/home/vscode/.config/neofetch/config.conf"
handle_file_ln "/home/vscode/.dotfiles/config/nvim/init.lua" "/home/vscode/.config/nvim/init.lua"
handle_file_ln "/home/vscode/.dotfiles/config/pip/pip.conf" "/home/vscode/.config/pip/pip.conf"
handle_file_ln "/home/vscode/.dotfiles/config/plasma-localerc" "/home/vscode/.config/plasma-localerc"
handle_file_ln "/home/vscode/.dotfiles/config/sublime-text/Packages/User/Preferences.sublime-settings" "/home/vscode/.config/sublime-text/Packages/User/Preferences.sublime-settings"
handle_file_ln "/home/vscode/.dotfiles/doom.d" "/home/vscode/.doom.d"
handle_file_ln "/home/vscode/.dotfiles/envrc" "/home/vscode/.envrc"
handle_file_ln "/home/vscode/.dotfiles/gemrc" "/home/vscode/.gemrc"
handle_file_ln "/home/vscode/.dotfiles/ghc/ghci.conf" "/home/vscode/.ghc/ghci.conf"
handle_file_ln "/home/vscode/.dotfiles/ghcup/config.yaml" "/home/vscode/.ghcup/config.yaml"
handle_file_ln "/home/vscode/.dotfiles/gitconfig" "/home/vscode/.gitconfig"
handle_file_ln "/home/vscode/.dotfiles/gitignore_global" "/home/vscode/.gitignore_global"
handle_file_ln "/home/vscode/.dotfiles/gnupg/gpg-agent.conf" "/home/vscode/.gnupg/gpg-agent.conf"
handle_file_ln "/home/vscode/.dotfiles/gnupg/gpg.conf" "/home/vscode/.gnupg/gpg.conf"
handle_file_ln "/home/vscode/.dotfiles/gradle/gradle.properties" "/home/vscode/.gradle/gradle.properties"
handle_file_ln "/home/vscode/.dotfiles/hgrc" "/home/vscode/.hgrc"
handle_file_ln "/home/vscode/.dotfiles/irbrc" "/home/vscode/.irbrc"
handle_file_ln "/home/vscode/.dotfiles/mill/ammonite/predef.sc" "/home/vscode/.mill/ammonite/predef.sc"
handle_file_ln "/home/vscode/.dotfiles/npmrc" "/home/vscode/.npmrc"
handle_file_ln "/home/vscode/.dotfiles/nuget/NuGet/NuGet.Config" "/home/vscode/.nuget/NuGet/NuGet.Config"
handle_file_ln "/home/vscode/.dotfiles/ocamlinit" "/home/vscode/.ocamlinit"
handle_file_ln "/home/vscode/.dotfiles/psqlrc" "/home/vscode/.psqlrc"
handle_file_ln "/home/vscode/.dotfiles/rustup/settings.toml" "/home/vscode/.rustup/settings.toml"
handle_file_ln "/home/vscode/.dotfiles/spacemacs" "/home/vscode/.spacemacs"
handle_file_ln "/home/vscode/.dotfiles/ssh/config" "/home/vscode/.ssh/config"
handle_file_ln "/home/vscode/.dotfiles/stack/config.yaml" "/home/vscode/.stack/config.yaml"
handle_file_ln "/home/vscode/.dotfiles/tmux.conf" "/home/vscode/.tmux.conf"
handle_file_ln "/home/vscode/.dotfiles/xprofile" "/home/vscode/.xprofile"
handle_file_ln "/home/vscode/.dotfiles/zshrc" "/home/vscode/.zshrc"
